//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG3LocalizationMerger.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG3LocalizationMerger.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        public static string CanceledMessage {
            get {
                return ResourceManager.GetString("CanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0} to {1}....
        /// </summary>
        public static string ConvertingMessage {
            get {
                return ResourceManager.GetString("ConvertingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        public static string Dialogs {
            get {
                return ResourceManager.GetString("Dialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogues.
        /// </summary>
        public static string Dialogues {
            get {
                return ResourceManager.GetString("Dialogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete!.
        /// </summary>
        public static string ExportCompleteMessage {
            get {
                return ResourceManager.GetString("ExportCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File Path.
        /// </summary>
        public static string ExportPath {
            get {
                return ResourceManager.GetString("ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}....
        /// </summary>
        public static string ExtractingMessage {
            get {
                return ResourceManager.GetString("ExtractingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        public static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}..
        /// </summary>
        public static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Descriptions.
        /// </summary>
        public static string ItemDescriptions {
            get {
                return ResourceManager.GetString("ItemDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Names.
        /// </summary>
        public static string ItemNames {
            get {
                return ResourceManager.GetString("ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Pack.
        /// </summary>
        public static string LanguagePack {
            get {
                return ResourceManager.GetString("LanguagePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} loaded. Time spent: {2:0.##}s.
        /// </summary>
        public static string LoadedMessage {
            get {
                return ResourceManager.GetString("LoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge EVERYTHING.
        /// </summary>
        public static string MergeUnconditionally {
            get {
                return ResourceManager.GetString("MergeUnconditionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION.
        /// </summary>
        public static string MergeUnconditionallyTitle {
            get {
                return ResourceManager.GetString("MergeUnconditionallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will merge EVERYTHING, including those not on the list.
        ///It will cause overflow on some UI texts.
        ///
        ///Do you wish to continue?.
        /// </summary>
        public static string MergeUnconditionallyWarning {
            get {
                return ResourceManager.GetString("MergeUnconditionallyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging {0}....
        /// </summary>
        public static string MergingMessage {
            get {
                return ResourceManager.GetString("MergingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging all string....
        /// </summary>
        public static string MergingUnconditionallyMessage {
            get {
                return ResourceManager.GetString("MergingUnconditionallyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscs.
        /// </summary>
        public static string Miscs {
            get {
                return ResourceManager.GetString("Miscs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string NotExistMessage {
            get {
                return ResourceManager.GetString("NotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create package due to I/O error.
        ///Please make sure the game is not running.
        ///
        ///Retry?.
        /// </summary>
        public static string PackageErrorMessage {
            get {
                return ResourceManager.GetString("PackageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging....
        /// </summary>
        public static string PackagingMessage {
            get {
                return ResourceManager.GetString("PackagingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Descriptions.
        /// </summary>
        public static string QuestDescriptions {
            get {
                return ResourceManager.GetString("QuestDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Markers.
        /// </summary>
        public static string QuestMarkers {
            get {
                return ResourceManager.GetString("QuestMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Names.
        /// </summary>
        public static string QuestNames {
            get {
                return ResourceManager.GetString("QuestNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Language Pack.
        /// </summary>
        public static string ReferencePack {
            get {
                return ResourceManager.GetString("ReferencePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}....
        /// </summary>
        public static string SavingMessage {
            get {
                return ResourceManager.GetString("SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Data....
        /// </summary>
        public static string SortingDataMessage {
            get {
                return ResourceManager.GetString("SortingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Descriptions.
        /// </summary>
        public static string StatusDescriptions {
            get {
                return ResourceManager.GetString("StatusDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Names.
        /// </summary>
        public static string StatusNames {
            get {
                return ResourceManager.GetString("StatusNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Reference.
        /// </summary>
        public static string SwapReference {
            get {
                return ResourceManager.GetString("SwapReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG3 Localization Merger.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips.
        /// </summary>
        public static string Tooltips {
            get {
                return ResourceManager.GetString("Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total elapsed: {0:0.##}s.
        /// </summary>
        public static string TotalElapsedMessage {
            get {
                return ResourceManager.GetString("TotalElapsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total strings: {0} Matched: {1}.
        /// </summary>
        public static string TotalStringMessage {
            get {
                return ResourceManager.GetString("TotalStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacked Data Folder.
        /// </summary>
        public static string UnpackedData {
            get {
                return ResourceManager.GetString("UnpackedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints.
        /// </summary>
        public static string Waypoints {
            get {
                return ResourceManager.GetString("Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
